[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200
  force = true


